@startuml
title
Activity diagram for the game "Gravitrips"
end title

start
:вывод кратких инструкций
пользователю;
:установка начальных условий и ограничений;
note right
Допущения и ограничения:
- размер игрового поля 6(строк) х 7 (столбцы);
- количество матчей произвольное;
- количество игр в матче произвольное;
- между собой играют два игрока HUMAN & COMPUTER
- в рамках одного матча типы игроков не меняются;
- 1-й игрок в качестве фишек использует "Х;
- 2-й игрок в качестве фишек использует "0";
- в 1-й игре матча первым ходит 1-й игрок, далее по очереди;
- для хода COMPUTER используем генеретор случайных чисел.
end note

repeat
:установка нового матча;
:выбор, кто с кем играет;
repeat

partition Game  {
:установка новой игры в матче;
repeat
if (все ячейки заполнены?) then (да)
:заканчиваем игру - ничья;
endif
if (заканчиваем игру?) then (нет)
:определяем, чья очередь ходить;
repeat
:игрок делает ход;
repeat while (ход корректный?)
if ( игрок выиграл?) then (да)
:заканчиваем игру - игрок выиграл;
endif
endif
repeat while (заканчиваем игру?)
:выдача результата текущей игры, кто выиграл;
}

:формирование и выдача результатов матча;
repeat while (продолжаем матч?)
:поздравление победителю матча;
repeat while (играем ещё матч?)

stop
@enduml